/**
 * AI Model configurations
 * Defines parameters and settings for each supported AI image generation model
 * Each model has specific prompt syntax and capability support
 */

import type { AIModel, ModelConfig } from './types';

export const modelConfigs: Record<AIModel, ModelConfig> = {
  midjourney: {
    name: 'Midjourney',
    icon: '🎨',
    maxCreativity: 1000,
    creativityParam: '--stylize',
    variationParam: '--chaos',
    negativeParam: '--no',
    aspectParam: '--ar',
    supportsNegativePrompt: true,
    promptStyle: 'tags',
  },
  flux: {
    name: 'Flux',
    icon: '⚡',
    maxCreativity: 20,
    creativityParam: 'guidance_scale:',
    variationParam: 'variation:',
    negativeParam: '',
    aspectParam: 'aspect:',
    supportsNegativePrompt: false,
    promptStyle: 'natural',
  },
  'stable-diffusion': {
    name: 'Stable Diffusion',
    icon: '🔮',
    maxCreativity: 30,
    creativityParam: 'CFG Scale:',
    variationParam: 'Variation:',
    negativeParam: 'Negative prompt:',
    aspectParam: 'Size:',
    supportsNegativePrompt: true,
    promptStyle: 'tags',
  },
  dalle3: {
    name: 'DALL-E 3',
    icon: '🌟',
    maxCreativity: 100,
    creativityParam: 'style:',
    variationParam: 'quality:',
    negativeParam: '',
    aspectParam: 'size:',
    supportsNegativePrompt: false,
    promptStyle: 'natural',
  },
  chatgpt: {
    name: 'ChatGPT',
    icon: '💬',
    maxCreativity: 100,
    creativityParam: '',
    variationParam: '',
    negativeParam: 'without',
    aspectParam: '',
    supportsNegativePrompt: true,
    promptStyle: 'natural',
  },
  imagen: {
    name: 'Imagen 3',
    icon: '🌈',
    maxCreativity: 100,
    creativityParam: 'creativity:',
    variationParam: 'seed_variation:',
    negativeParam: 'negative_prompt:',
    aspectParam: 'aspect_ratio:',
    supportsNegativePrompt: true,
    promptStyle: 'natural',
  },
  ideogram: {
    name: 'Ideogram',
    icon: '✨',
    maxCreativity: 100,
    creativityParam: '--style',
    variationParam: '--variation',
    negativeParam: '--negative',
    aspectParam: '--aspect',
    supportsNegativePrompt: true,
    promptStyle: 'tags',
  },
  leonardo: {
    name: 'Leonardo.ai',
    icon: '🎭',
    maxCreativity: 100,
    creativityParam: 'guidance_scale:',
    variationParam: 'preset_style:',
    negativeParam: 'negative_prompt:',
    aspectParam: 'dimensions:',
    supportsNegativePrompt: true,
    promptStyle: 'natural',
  },
  firefly: {
    name: 'Adobe Firefly',
    icon: '🔥',
    maxCreativity: 100,
    creativityParam: 'style_strength:',
    variationParam: 'variation:',
    negativeParam: '',
    aspectParam: 'aspect_ratio:',
    supportsNegativePrompt: false,
    promptStyle: 'natural',
  },
};
